# DO NOT EDIT THIS FILE!
#
# Python module MIDI generated by omniidl

import omniORB
omniORB.updateModule("MIDI")

# ** 1. Stub files contributing to this module
import MIDIDataType_idl

# ** 2. Sub-modules

# ** 3. End
