# DO NOT EDIT THIS FILE!
#
# Python module MIDI__POA generated by omniidl

import omniORB
omniORB.updateModule("MIDI__POA")

# ** 1. Stub files contributing to this module
import MIDIDataType_idl

# ** 2. Sub-modules

# ** 3. End
